"""Generate draft findings from deterministic pattern analysis.

For high-confidence patterns where the vulnerability can be verified
programmatically (not just grepped), generates structured draft findings
that agents verify rather than discover from scratch.

The agent's job shifts from "find the needle" to "is this needle sharp?"
"""
from __future__ import annotations

import os
import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class DraftFinding:
    pattern_id: str
    title: str
    file: str
    line: int
    severity: str
    evidence: str
    impact: str
    category: str


def generate_drafts(source_root: str, language: str = "go") -> list[DraftFinding]:
    """Run all deterministic checks and return draft findings."""
    drafts: list[DraftFinding] = []

    raw: list[DraftFinding] = []
    raw.extend(_check_tekton_mutable_refs(source_root))
    raw.extend(_check_metrics_no_auth(source_root))
    raw.extend(_check_pprof_enabled(source_root))
    raw.extend(_check_unpinned_base_images(source_root))

    seen: set[str] = set()
    drafts: list[DraftFinding] = []
    for d in raw:
        key = d.pattern_id
        if key not in seen:
            seen.add(key)
            drafts.append(d)

    return drafts


def format_drafts_md(drafts: list[DraftFinding]) -> str:
    """Format draft findings as markdown for the dispatch directory."""
    if not drafts:
        return ""

    lines = [
        "## Draft Findings (Programmatically Generated)\n",
        "These findings were generated by deterministic code analysis.",
        "You MUST verify each draft by reading the source file.",
        "For each draft: **CONFIRM** (include as-is or adjust severity)",
        "or **REJECT** with specific evidence why it is not exploitable.\n",
    ]

    for i, d in enumerate(drafts, 1):
        lines.append(f"### DRAFT-{i}: {d.title}")
        lines.append(f"- **File:** {d.file}:{d.line}")
        lines.append(f"- **Severity:** {d.severity}")
        lines.append(f"- **Category:** {d.category}")
        lines.append(f"- **Evidence:** {d.evidence}")
        lines.append(f"- **Impact:** {d.impact}")
        lines.append(f"- **Action:** CONFIRM this as a finding (copy into your output")
        lines.append(f"  with a SEC-NNN ID) or REJECT with specific mitigation evidence.\n")

    return "\n".join(lines)


def _grep(source_root: str, pattern: str, includes: list[str] | None = None,
          exclude_tests: bool = True) -> list[tuple[str, int, str]]:
    """Run grep and return (file, line, content) tuples."""
    cmd = ["grep", "-rn", "--fixed-strings"]
    for inc in (includes or ["*.go", "*.yaml", "*.yml"]):
        cmd.extend(["--include", inc])
    for skip in ("vendor", ".gopath-loader", ".git", "bin",
                  "node_modules", "config/crd", "rhoai-bundle"):
        cmd.extend(["--exclude-dir", skip])
    cmd.append(pattern)
    cmd.append(".")

    try:
        proc = subprocess.run(
            cmd, capture_output=True, text=True,
            cwd=source_root, timeout=15,
        )
    except (subprocess.TimeoutExpired, OSError):
        return []

    results = []
    for line in proc.stdout.splitlines():
        parts = line.split(":", 2)
        if len(parts) < 3:
            continue
        filepath = parts[0].lstrip("./")
        if exclude_tests and ("_test.go" in filepath or "testdata/" in filepath):
            continue
        try:
            lineno = int(parts[1])
        except ValueError:
            continue
        results.append((filepath, lineno, parts[2].strip()))

    return results


def _check_tekton_mutable_refs(source_root: str) -> list[DraftFinding]:
    """Check for Tekton pipelineRef with mutable revision (e.g., revision: main)."""
    drafts = []

    resolver_hits = _grep(source_root, "resolver: git", ["*.yaml"])
    for filepath, lineno, content in resolver_hits:
        if "tekton/" not in filepath:
            continue

        fpath = os.path.join(source_root, filepath)
        if not os.path.isfile(fpath):
            fpath = os.path.join(source_root, "." + filepath)
        try:
            full_text = Path(fpath).read_text()
        except OSError:
            continue

        revision_match = re.search(
            r"name:\s*revision\s*\n\s*value:\s*['\"]?(main|master|develop)['\"]?",
            full_text,
        )
        if not revision_match:
            revision_match = re.search(
                r"revision:\s*['\"]?(main|master|develop)['\"]?",
                full_text,
            )
        if not revision_match:
            continue

        rev_line = full_text[:revision_match.start()].count("\n") + 1

        drafts.append(DraftFinding(
            pattern_id="tekton_mutable_ref",
            title=f"Tekton PipelineRun uses mutable branch ref (revision: {revision_match.group(1)})",
            file=filepath,
            line=rev_line,
            severity="Medium",
            evidence=(
                f"pipelineRef uses resolver: git with revision: {revision_match.group(1)} "
                f"(mutable branch). A compromised upstream repo can inject malicious "
                f"build steps. SLSA Level 2 requires pinning to immutable ref (commit SHA)."
            ),
            impact="Supply chain: compromised upstream injects build steps into CI/CD pipeline",
            category="supply_chain",
        ))

    return drafts


def _check_metrics_no_auth(source_root: str) -> list[DraftFinding]:
    """Check for metrics endpoint bound to 0.0.0.0 without TLS/auth."""
    drafts = []

    hits = _grep(source_root, "metrics-bind-address")
    zero_hits = [h for h in hits if "0.0.0.0" in h[2]]

    if not zero_hits:
        return []

    secure_hits = _grep(source_root, "SecureMetrics")
    has_secure = len(secure_hits) > 0

    if has_secure:
        return []

    for filepath, lineno, content in zero_hits:
        drafts.append(DraftFinding(
            pattern_id="metrics_no_auth",
            title="Metrics endpoint bound to 0.0.0.0 without TLS or authentication",
            file=filepath,
            line=lineno,
            severity="Medium",
            evidence=(
                f"{filepath}:{lineno}: `{content[:100]}`. "
                f"Binds to all interfaces without SecureMetrics or TLS. "
                f"Any pod in the network can scrape controller-runtime metrics."
            ),
            impact="Information disclosure: Go runtime stats, reconciliation counts, queue depths",
            category="unauthenticated_endpoint",
        ))

    return drafts


def _check_pprof_enabled(source_root: str) -> list[DraftFinding]:
    """Check for pprof debug endpoint configurable via flag/env."""
    drafts = []

    hits = _grep(source_root, "pprof-bind-address", ["*.go"])
    if not hits:
        return []

    flag_hits = [h for h in hits if "flag" in h[2].lower() or "pflag" in h[2].lower()
                 or "BindEnv" in h[2] or "mapstructure" in h[2]]

    if not flag_hits:
        return []

    drafts.append(DraftFinding(
        pattern_id="pprof_configurable",
        title="Pprof debug endpoint configurable via flag and environment variable",
        file=flag_hits[0][0],
        line=flag_hits[0][1],
        severity="Low",
        evidence=(
            f"pprof-bind-address plumbed via flags/env. Disabled by default "
            f"(empty string) but any user with config access can enable it. "
            f"Pprof exposes goroutine dumps and heap profiles which can leak "
            f"in-memory secrets."
        ),
        impact="Config access enables profiling endpoint -> memory dumps reveal secrets",
        category="debug_endpoint",
    ))

    return drafts


def _check_unpinned_base_images(source_root: str) -> list[DraftFinding]:
    """Check for unpinned :latest tags in Dockerfiles."""
    drafts = []

    for dockerfile in ["Dockerfile", "Dockerfiles/Dockerfile",
                       "Dockerfiles/rhoai.Dockerfile", "Containerfile",
                       "Containerfile.server"]:
        fpath = os.path.join(source_root, dockerfile)
        if not os.path.isfile(fpath):
            continue

        try:
            content = Path(fpath).read_text()
        except OSError:
            continue

        for i, line in enumerate(content.splitlines(), 1):
            if line.strip().startswith("#"):
                continue
            if re.match(r'^\s*FROM\s+', line) and ":latest" in line:
                if "@sha256:" in line:
                    continue
                drafts.append(DraftFinding(
                    pattern_id="unpinned_dockerfile",
                    title=f"Base image uses unpinned :latest tag in {dockerfile}",
                    file=dockerfile,
                    line=i,
                    severity="Minor",
                    evidence=f"Line {i}: `{line.strip()[:100]}`. Mutable tag without digest pinning.",
                    impact="Supply chain: base image replacement if build system fails to pin",
                    category="supply_chain",
                ))

    return drafts
